
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    UserViewSet, PostViewSet, CategoryViewSet, 
    TagViewSet, CommentViewSet, AnalyticsViewSet
)

# Create router and register viewsets
router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'posts', PostViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'tags', TagViewSet)
router.register(r'comments', CommentViewSet)
router.register(r'analytics', AnalyticsViewSet, basename='analytics')

# The API URLs are now determined automatically by the router.
urlpatterns = [
    path('', include(router.urls)),
]

# URL patterns generated by the router:
# GET /api/v1/users/ - List all users
# POST /api/v1/users/ - Create new user
# GET /api/v1/users/{id}/ - Retrieve user
# PUT /api/v1/users/{id}/ - Update user
# PATCH /api/v1/users/{id}/ - Partial update user
# DELETE /api/v1/users/{id}/ - Delete user
# GET /api/v1/users/me/ - Current user profile
# PATCH /api/v1/users/update_profile/ - Update current user
# GET /api/v1/users/{id}/posts/ - User's posts

# GET /api/v1/posts/ - List all posts
# POST /api/v1/posts/ - Create new post
# GET /api/v1/posts/{id}/ - Retrieve post
# PUT /api/v1/posts/{id}/ - Update post
# PATCH /api/v1/posts/{id}/ - Partial update post
# DELETE /api/v1/posts/{id}/ - Delete post
# POST /api/v1/posts/{id}/like/ - Like/unlike post
# GET /api/v1/posts/featured/ - Featured posts
# GET /api/v1/posts/popular/ - Popular posts
# GET /api/v1/posts/trending/ - Trending posts
# GET /api/v1/posts/my_posts/ - Current user's posts

# Similar patterns for categories, tags, comments, and analytics
